import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
} from 'docx'

import { supabaseAdmin } from './supabase-admin'

function parseInlineMarkdown(text: string): TextRun[] {
  const parts = text.split(/(\*\*[^*]+\*\*)/g)
  return parts.flatMap((part) => {
    const boldMatch = part.match(/^\*\*(.+)\*\*$/)
    if (boldMatch) {
      return [
        new TextRun({
          text: boldMatch[1],
          bold: true,
        }),
      ]
    }

    return [
      new TextRun({
        text: part,
      }),
    ]
  })
}

function createParagraphFromLine(text: string): Paragraph {
  if (text.startsWith('# ')) {
    return new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: parseInlineMarkdown(text.replace('# ', '')),
    })
  }

  if (text.startsWith('## ')) {
    return new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: parseInlineMarkdown(text.replace('## ', '')),
    })
  }

  if (text.startsWith('### ')) {
    return new Paragraph({
      heading: HeadingLevel.HEADING_3,
      children: parseInlineMarkdown(text.replace('### ', '')),
    })
  }

  if (text.startsWith('- ') || text.startsWith('* ')) {
    return new Paragraph({
      bullet: {
        level: 0,
      },
      children: parseInlineMarkdown(text.substring(2)),
    })
  }

  return new Paragraph({
    children: parseInlineMarkdown(text),
    spacing: {
      after: 180,
    },
  })
}

export async function generateDocument(
  content: string,
  title: string,
  userId: string,
  conversationId: string
) {
  // Split AI response into lines
  const lines = content.split('\n')

  const children: Paragraph[] = []

  // Cover Page
  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [
        new TextRun({
          text: title,
          bold: true,
          size: 40,
        }),
      ],
      spacing: {
        after: 600,
      },
    })
  )

  children.push(
    new Paragraph({
      text: `Generated by AI Workspace`,
      spacing: {
        after: 800,
      },
    })
  )

  // Document Body

  for (const line of lines) {
    const text = line.trim()

    if (!text) {
      children.push(new Paragraph(''))
      continue
    }

    children.push(createParagraphFromLine(text))
  }

  const doc = new Document({
    sections: [
      {
        children,
      },
    ],
  })

  const buffer = await Packer.toBuffer(doc)

  const fileName = `${Date.now()}.docx`

  const filePath = `${userId}/${conversationId}/${fileName}`

  const { error } = await supabaseAdmin.storage
    .from('documents')
    .upload(filePath, buffer, {
      contentType:
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      upsert: false,
    })

  if (error) {
    throw error
  }

  const { data } = await supabaseAdmin.storage
    .from('documents')
    .createSignedUrl(filePath, 60 * 60)

  if (!data?.signedUrl) {
    throw new Error(
      'Unable to create download URL'
    )
  }

  return data.signedUrl
}